apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 5
  selector:
    name: web
    spec:
      containers:
      - image: node:8
        command: ['/bin/sh', '-c']
        args: ['cd /home && git clone https://github.com/madhuhaasnannaka/simple-nodejs-k8s.git demo && cd demo/sample-app && npm install && node server.js']
        name: web
        ports:
        - containerPort: 3000
          name: http-server

